DROP TABLE IF EXISTS fact_tournament_battles;

CREATE TABLE IF NOT EXISTS fact_tournament_battles (
    battle_id             INTEGER,
    pokemon1_id           INTEGER,
    pokemon1_name         TEXT,
    pokemon1_type1        TEXT,
    pokemon1_type2        TEXT,
    pokemon1_hp           REAL,
    pokemon1_attack       REAL,
    pokemon1_defense      REAL,
    pokemon1_speed        REAL,
    pokemon1_legendary    INTEGER,
    trainer1_id           INTEGER,
    trainer1_name         TEXT,
    trainer1_age          INTEGER,
    trainer1_city         TEXT,
    pokemon2_id           INTEGER,
    pokemon2_name         TEXT,
    pokemon2_type1        TEXT,
    pokemon2_type2        TEXT,
    pokemon2_types        TEXT,
    pokemon2_hp           REAL,
    pokemon2_attack       REAL,
    pokemon2_defense      REAL,
    pokemon2_speed        REAL,
    pokemon2_legendary    INTEGER,
    trainer2_id           INTEGER,
    trainer2_name         TEXT,
    trainer2_age          INTEGER,
    trainer2_city         TEXT,
    winner_trainer_id     INTEGER NULL,
    battle_status         TEXT,
    last_update_ts        TEXT
);
